### ISSUE TITLE
KeySelectorRange.starts_with with NestedTuple coder error

### ISSUE THREAD

**Issue by WolfDan** [ananthakumaran/fdb#7]
Hello,

I have this code for indexing some properties:

```elixir
Transaction.Coder.new(
      Subspace.new(
        index_dir,
        Tuple.new({
          # property_name
          ByteString.new(),
          # property_value
          Dynamic.new(),
          # node_uid
          get_uid_coder()
        })
      ),
      # dummy_value, nil
      GraphValue.new()
    )

defp get_uid_coder() do
    NestedTuple.new({ByteString.new(), Integer.new()})
 end
```

I added a few values as test in fdb, and then query the range, but I'm getting an error when I call `Enum.to_list()`

this is the code:

```elixir
Database.transact(db, fn tr ->
      [{_key, state} | _] =
        :ets.lookup(:database_state, Nomure.TransactionUtils.get_database_state_key())

      range = FDB.KeySelectorRange.starts_with({"name", {:unicode_string, "Sif"}})

      FDB.Transaction.get_range(tr, range, %{coder: state.properties_index.coder})
      |> Enum.to_list()
      |> IO.inspect()
    end)
```

The error

```
** (FunctionClauseError) no function clause matching in FDB.Coder.NestedTuple.decode/2

     The following arguments were given to FDB.Coder.NestedTuple.decode/2:

         # 1
         ""

         # 2
         [%FDB.Coder{module: FDB.Coder.ByteString, opts: {:bm, #Reference<0.177895559.919994369.9123>}}, %FDB.Coder{module: FDB.Coder.Integer, opts: nil}]

     Attempted function clauses (showing 1 out of 1):

         def decode(-<<(<<5>>::binary()), rest::binary()>>-, coders)

     code: Database.transact(db, fn tr ->
     stacktrace:
       (fdb) lib/fdb/coder/nested_tuple.ex:23: FDB.Coder.NestedTuple.decode/2
       (fdb) lib/fdb/coder/tuple.ex:24: anonymous fn/2 in FDB.Coder.Tuple.decode/2
       (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
       (fdb) lib/fdb/transaction/coder.ex:30: FDB.Transaction.Coder.decode_key/2
       (fdb) lib/fdb/transaction.ex:117: anonymous fn/2 in FDB.Transaction.decode_range_items/2
       (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
       (fdb) lib/fdb/transaction.ex:252: anonymous fn/6 in FDB.Transaction.get_range/3
       (elixir) lib/stream.ex:1482: Stream.do_unfold/4
       (elixir) lib/stream.ex:857: Stream.do_transform/5
       (elixir) lib/enum.ex:2979: Enum.reverse/1
       (elixir) lib/enum.ex:2613: Enum.to_list/1
       test/nomure_test.exs:42: anonymous fn/1 in NomureTest."test node exist?"/1
       (fdb) lib/fdb/database.ex:129: FDB.Database.do_transact/2
       test/nomure_test.exs:35: (test)
```

Did I'm missing something on the `starts_with` function? Or it's a bug? I'm not giving the uid param which is a tuple that contains `{:string, :integer}`

The full code is here: https://github.com/OkamiIO/Nomure/blob/master/test/nomure_test.exs#L35

Thank you!

**Comment by ananthakumaran** [comment]
I am on vacation, so haven't been able to test my theory. Dynamic coder is
greedy. So it could only be used as the last element of the tuple. It seems
like the range query is working correctly. The error happens when the
returned value is decoded. Dynamic coder consumes all the string and leaves
nothing for uid coder.
